<a href="https://colab.research.google.com/github/Sharmaluvkesh/Movie-Genre-Classification---Machine-Learning-Approach/blob/main/movie_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Movie Genre Classification - Machine Learning Approach
This notebook contains a complete Machine Learning workflow to perform multiclass classification on the provided movie dataset.

### **Import the dependencies**

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

### **Load the dataset**

In [2]:
df = pd.read_csv('movie_genre_classification_final.csv')
print('--- First 5 Rows ---')
print(df.head())
print('\n--- Data Shape ---')
print(df.shape)
print('\n--- Data Info ---')
df.info()

--- First 5 Rows ---
             Title  Year  Director  Duration  Rating   Votes  \
0  Winds of Fate 4  1980    R. Lee       167     4.1  182425   
1     Firestorm 11  2014   S. Chen       166     4.1  449351   
2    Silent Echo 2  2016   A. Khan       170     4.1  363328   
3    City Lights 4  1982  L. Zhang       170     9.9   62371   
4   Broken Truth 1  1990  L. Zhang        91     5.3    4600   

                                         Description  Language Country  \
0   A touching love story with heartwarming moments.   Spanish   China   
1  A fast-paced thriller with intense action scenes.    Korean   China   
2  A fast-paced thriller with intense action scenes.    Korean   Japan   
3  An emotional journey exploring complex charact...  Japanese   Japan   
4  An imaginative world filled with magic and won...    Korean     USA   

   Budget_USD  BoxOffice_USD    Genre Production_Company Content_Rating  \
0    39979615      179936008  Romance         DreamWorks              R   

* Data is **Balanced** across genres.

In [3]:
print(df['Genre'].value_counts())
df = df.drop(columns=['Title'])
df.info()

Genre
Horror      7260
Drama       7187
Romance     7169
Thriller    7118
Action      7107
Fantasy     7100
Comedy      7059
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Year                50000 non-null  int64  
 1   Director            50000 non-null  object 
 2   Duration            50000 non-null  int64  
 3   Rating              50000 non-null  float64
 4   Votes               50000 non-null  int64  
 5   Description         50000 non-null  object 
 6   Language            50000 non-null  object 
 7   Country             50000 non-null  object 
 8   Budget_USD          50000 non-null  int64  
 9   BoxOffice_USD       50000 non-null  int64  
 10  Genre               50000 non-null  object 
 11  Production_Company  50000 non-null  object 
 12  Content_Rating      50000 non-null  object 
 13  

### **Preprocess and Encode Features**

In [4]:
le = LabelEncoder()
df['Genre'] = le.fit_transform(df['Genre'])
df = pd.get_dummies(df, columns=['Description', 'Language', 'Country', 'Production_Company', 'Content_Rating', 'Lead_Actor', 'Director'], drop_first=True)
df.head()

,Year,Duration,Rating,Votes,Budget_USD,BoxOffice_USD,Genre,Num_Awards,Critic_Reviews,Description_A light-hearted comedy that guarantees laughter.,...,Lead_Actor_Tom Hanks,Director_D. Patel,Director_J. Smith,Director_L. Zhang,Director_M. Brown,Director_N. Roy,Director_P. Adams,Director_R. Lee,Director_S. Chen,Director_T. Johnson
0,1980,167,4.1,182425,39979615,179936008,5,8,229,False,...,False,False,False,False,False,False,False,True,False,False
1,2014,166,4.1,449351,116404774,802121619,0,20,466,False,...,False,False,False,False,False,False,False,False,True,False
2,2016,170,4.1,363328,166261330,225526871,0,16,539,False,...,False,False,False,False,False,False,False,False,False,False
3,1982,170,9.9,62371,28861315,69813738,2,15,606,False,...,False,False,False,True,False,False,False,False,False,False
4,1990,91,5.3,4600,43890403,375136716,3,6,330,False,...,False,False,False,True,False,False,False,False,False,False


### **Split Features and Targets**

In [5]:
x = df.drop(columns='Genre', axis=1)
y = df['Genre']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)
print("Training dimensions:", x_train.shape)

Training dimensions: (40000, 57)


### **Feature Scaling**

In [6]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

### **Building and Training the Machine Learning Model**

In [7]:
model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=42)

### **Generate Training Predictions**

In [8]:
train_pred = model.predict(x_train)
train_pred

array([6, 0, 0, ..., 2, 6, 5])

### **Generate Testing Predictions**

In [9]:
test_pred = model.predict(x_test)
test_pred

array([1, 0, 1, ..., 0, 3, 3])

### **Model Evaluation**

In [10]:
print('Train Acc :-', accuracy_score(y_train, train_pred))
print('Test Acc :-', accuracy_score(y_test, test_pred))

print('\nTrain Confusion Matrix :-\n', confusion_matrix(y_train, train_pred))
print('Test Confusion Matrix :-\n', confusion_matrix(y_test, test_pred))

print('\nTrain Precision :-', precision_score(y_train, train_pred, average='macro'))
print('Test Precision :-', precision_score(y_test, test_pred, average='macro'))

print('\nTrain Recall :-', recall_score(y_train, train_pred, average='macro'))
print('Test Recall :-', recall_score(y_test, test_pred, average='macro'))

Train Acc :- 1.0
Test Acc :- 1.0

Train Confusion Matrix :-
 [[5683    0    0    0    0    0    0]
 [   0 5626    0    0    0    0    0]
 [   0    0 5756    0    0    0    0]
 [   0    0    0 5714    0    0    0]
 [   0    0    0    0 5804    0    0]
 [   0    0    0    0    0 5694    0]
 [   0    0    0    0    0    0 5723]]
Test Confusion Matrix :-
 [[1424    0    0    0    0    0    0]
 [   0 1433    0    0    0    0    0]
 [   0    0 1431    0    0    0    0]
 [   0    0    0 1386    0    0    0]
 [   0    0    0    0 1456    0    0]
 [   0    0    0    0    0 1475    0]
 [   0    0    0    0    0    0 1395]]

Train Precision :- 1.0
Test Precision :- 1.0

Train Recall :- 1.0
Test Recall :- 1.0
